### PR TITLE
Add Info Item component

### PR DESCRIPTION
**Pull request by madsobel**

### CODE REVIEW

**Comment by andersklenke** [comment]
Rename it to `InfoItem/index.jsx`. Other than that 👍

**Comment by madsobel** [comment]
@andersklenke I only think that files containing JSX should be named `.jsx`.
The sole purpose of that index file is to make a named export from the InfoItem component.

**Comment by andersklenke** [comment]
@madsobel Why not move the whole `InfoItem.jsx` into the index file and then export the `InfoItem`?

**Comment by madsobel** [comment]
That could also be an option. I think it's a matter of personal preference.
Which would you prefer?

**Comment by andersklenke** [comment]
I would prefer my solution. To me, the extra file just seems redundant.

**Comment by madsobel** [comment]
Got'cha. Then we'll do that with every component. I'll update this PR, and create a separate PR refactoring this in the other components.

**Pull request merged**
